### ISSUE TITLE
/favicon.ico request causes crash

### ISSUE THREAD

**Issue by guybedford** [zygo-io/zygo#2]
```
Error routing / : TypeError: Cannot read property 'options' of undefined
    at React.createClass.render (eval at __eval (/usr/local/lib/node_modules/zygo-cli/node_modules/zygo-server/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader-sans-promises.src.js:1533:105), <anonymous>:21:116)
    at ReactCompositeComponentMixin._renderValidatedComponent (evalmachine.<anonymous>:425:34)
    at wrapper [as _renderValidatedComponent] (evalmachine.<anonymous>:17:23)
    at ReactCompositeComponentMixin.mountComponent (evalmachine.<anonymous>:249:64)
    at wrapper [as mountComponent] (evalmachine.<anonymous>:17:23)
    at /usr/local/lib/node_modules/zygo-cli/node_modules/zygo-server/node_modules/react/lib/ReactServerRendering.js:40:38
    at ReactServerRenderingTransaction.Mixin.perform (/usr/local/lib/node_modules/zygo-cli/node_modules/zygo-server/node_modules/react/lib/Transaction.js:134:20)
    at Object.renderToString (/usr/local/lib/node_modules/zygo-cli/node_modules/zygo-server/node_modules/react/lib/ReactServerRendering.js:38:24)
    at _renderComponent.traceAllCss.then.then.then.result.component (/usr/local/lib/node_modules/zygo-cli/node_modules/zygo-server/build/render.js:39:18)
    at /usr/local/lib/node_modules/zygo-cli/node_modules/zygo-server/node_modules/traceur-runtime/index.js:1637:100
Error routing /favicon.ico : TypeError: Object.keys called on non-object
    at Function.keys (native)
    at _match (/usr/local/lib/node_modules/zygo-cli/node_modules/zygo-server/build/routes.js:29:10)
    at /usr/local/lib/node_modules/zygo-cli/node_modules/zygo-server/build/routes.js:42:20
    at Array.map (native)
    at _match (/usr/local/lib/node_modules/zygo-cli/node_modules/zygo-server/build/routes.js:41:30)
    at Object.match (/usr/local/lib/node_modules/zygo-cli/node_modules/zygo-server/build/routes.js:16:16)
    at /usr/local/lib/node_modules/zygo-cli/node_modules/zygo-server/build/zygo-server.js:65:22
    at /usr/local/lib/node_modules/zygo-cli/node_modules/zygo-server/node_modules/traceur-runtime/index.js:1637:100
    at promiseHandle (/usr/local/lib/node_modules/zygo-cli/node_modules/zygo-server/node_modules/traceur-runtime/index.js:1724:20)
    at /usr/local/lib/node_modules/zygo-cli/node_modules/zygo-server/node_modules/traceur-runtime/index.js:1718:9
```

Instead this should be firing a 404 Zygo not found.

**Comment by guybedford** [comment]
Moved to https://github.com/zygo-io/zygo-server/issues/1.
